### ISSUE TITLE
[Documentation bug] demo project doesn't work out of the box 

### ISSUE THREAD

**Issue by ka84** [john-doherty/selenium-cucumber-js#100]
Greetings,

Have just installed fresh node.js on my home mac, then created an emtpy folder to setup there a sample project with using your npm. Installation went fine, just few audit issues appeared in the end of installation (haven't yet looked at them):

```
iMac:tmp bugman$ cd tst/
iMac:tst bugman$ npm install selenium-cucumber-js --save-dev
npm WARN deprecated electron-prebuilt@1.4.13: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron
npm WARN deprecated phantomjs-prebuilt@2.1.12: this package is now deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request@2.74.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated mkdirp@0.5.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

> chromedriver@76.0.1 install /private/tmp/tst/node_modules/chromedriver
> node install.js

Current existing ChromeDriver binary is unavailable, proceding with download and extraction.
Downloading from file:  https://chromedriver.storage.googleapis.com/76.0.3809.126/chromedriver_mac64.zip
Saving to file: /var/folders/l0/tv525k695bjd9gwsdqyvxzw40000gn/T/76.0.3809.126/chromedriver/chromedriver_mac64.zip
Received 781K...
Received 1566K...
Received 2350K...
Received 3134K...
Received 3918K...
Received 4702K...
Received 5486K...
Received 6270K...
Received 7046K total.
Extracting zip contents
Copying to target path /private/tmp/tst/node_modules/chromedriver/lib/chromedriver
Fixing file permissions
Done. ChromeDriver binary available at /private/tmp/tst/node_modules/chromedriver/lib/chromedriver/chromedriver

> phantomjs-prebuilt@2.1.12 install /private/tmp/tst/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-macosx.zip
Saving to /var/folders/l0/tv525k695bjd9gwsdqyvxzw40000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip
Receiving...
  [=======================================-] 98%
Received 16746K total.
Extracting zip contents
Removing /private/tmp/tst/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /var/folders/l0/tv525k695bjd9gwsdqyvxzw40000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1586523957698/phantomjs-2.1.1-macosx -> /private/tmp/tst/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /private/tmp/tst/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs

> electron-chromedriver@1.8.0 install /private/tmp/tst/node_modules/selenium-cucumber-js/node_modules/electron-chromedriver
> node ./download-chromedriver.js

successfully dowloaded and extracted!

> electron@1.8.8 postinstall /private/tmp/tst/node_modules/electron
> node install.js

Downloading SHASUMS256.txt
[============================================>] 100.0% of 5.74 kB (5.74 kB/s)

> geckodriver@1.19.1 postinstall /private/tmp/tst/node_modules/geckodriver
> node index.js

Downloading geckodriver... Extracting... Complete.

> electron-prebuilt@1.4.13 postinstall /private/tmp/tst/node_modules/selenium-cucumber-js/node_modules/electron-prebuilt
> node install.js

npm WARN saveError ENOENT: no such file or directory, open '/private/tmp/tst/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/tst/package.json'
npm WARN tst No description
npm WARN tst No repository field.
npm WARN tst No README data
npm WARN tst No license field.

+ selenium-cucumber-js@1.7.0
added 461 packages from 494 contributors and audited 1743 packages in 317.791s

3 packages are looking for funding
  run `npm fund` for details

found 9 vulnerabilities (2 low, 6 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

```

But when I tried to run an example project - like from your docs on a project mainpage (https://www.npmjs.com/package/selenium-cucumber-js#demo) it threw an error:

```
iMac:tst bugman$ node ./node_modules/selenium-cucumber-js/index.js
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat '/private/tmp/tst/features'
    at Object.realpathSync (fs.js:1547:7)
    at Object.expandPathWithExtensions (/private/tmp/tst/node_modules/cucumber/lib/cucumber/cli/path_expander.js:14:23)
    at /private/tmp/tst/node_modules/cucumber/lib/cucumber/cli/path_expander.js:8:27
    at Array.map (<anonymous>)
    at Object.expandPathsWithExtensions (/private/tmp/tst/node_modules/cucumber/lib/cucumber/cli/path_expander.js:7:31)
    at Object.expandPaths (/private/tmp/tst/node_modules/cucumber/lib/cucumber/cli/feature_path_expander.js:9:38)
    at Function.Configuration (/private/tmp/tst/node_modules/cucumber/lib/cucumber/cli/configuration.js:21:63)
    at getConfiguration (/private/tmp/tst/node_modules/cucumber/lib/cucumber/cli.js:63:38)
    at Object.run (/private/tmp/tst/node_modules/cucumber/lib/cucumber/cli.js:69:27)
    at Object.<anonymous> (/private/tmp/tst/node_modules/selenium-cucumber-js/index.js:146:13) {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/private/tmp/tst/features'
}
``` 

To me it seems like it looks for an exsitance of a features folder (which I obviously don't have since I have just installed it and wanted to give it a first try ever). Probaly it's not the code bug, but rather documentation bug - bit confusing for the first-time-users of this thing. 
However I managed to get it working after navigating myself to the node_modules/selenium-cucumber-js and running it from there: 

```
cd ./node_modules/selenium-cucumber-js/
node index.js

```

**Comment by john-doherty** [comment]
This was a chromedriver version issue and is now fixed. Sorry for the delay
