### ISSUE TITLE
while installing, show ChromeDriver installation failed Error with http request:

### ISSUE THREAD

**Issue by Kilims** [john-doherty/selenium-cucumber-js#34]
Whole error

Downloading https://chromedriver.storage.googleapis.com/2.28/chromedriver_win32.zip
Saving to C:\GITWOR~1\VIMTHI~1\AppData\Local\Temp\chromedriver\chromedriver_win32.zip
Receiving...
ChromeDriver installation failed Error with http request: { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'text/html; charset=utf-8',
  'proxy-connection': 'close',
  connection: 'close',
  'content-length': '756' }
npm WARN nightwatch-0.9.16@1.0.0 No description
npm WARN nightwatch-0.9.16@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chromedriver@2.28.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.28.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

how to deal with it ?

**Comment by id4automation** [comment]
I am facing this issue as well. But chromeDriver and PhantomJS installed successfully. Its stuck with geckodriver with the below error 

> geckodriver@1.1.2 postinstall C:\Users\A632694\AppData\Roaming\npm\node_modules\selenium-cucumber-js\node_modules\geckodriver
> node index.js

```
Downloading geckodriver...
events.js:183
      throw er; // Unhandled 'error' event
      ^
RequestError: getaddrinfo ENOTFOUND github.com github.com:443
    at ClientRequest.<anonymous> (C:\Users\A632694\AppData\Roaming\npm\node_modules\selenium-cucumber-js\node_modules\got\index.js:69:21)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm WARN Error: EPERM: operation not permitted, rmdir 'C:\Users\A632694\AppData\Roaming\npm\node_modules'
npm WARN  { Error: EPERM: operation not permitted, rmdir 'C:\Users\A632694\AppData\Roaming\npm\node_modules'
npm WARN   stack: 'Error: EPERM: operation not permitted, rmdir \'C:\\Users\\A632694\\AppData\\Roaming\\npm\\node_modules\'',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'rmdir',
npm WARN   path: 'C:\\Users\\A632694\\AppData\\Roaming\\npm\\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geckodriver@1.1.2 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the geckodriver@1.1.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


```
