### ISSUE TITLE
extra failure with new "eyes" integration

### ISSUE THREAD

**Issue by bricas** [john-doherty/selenium-cucumber-js#42]
I've installed the latest version (1.5.1) with the "eyes" integration -- which i don't actually use.

When i get a failure in my tests, i now also get the following:

```
Error: Promise factory was not initialized with proper callback
at PromiseFactory.makePromise (/var/lib/jenkins/workspace/unb-lib-tests/node_modules/eyes.utils/src/PromiseFactory.js:49:15)
at EyesBase.abortIfNotClosed (/var/lib/jenkins/workspace/unb-lib-tests/node_modules/eyes.sdk/src/EyesBase.js:968:32)
at /var/lib/jenkins/workspace/unb-lib-tests/node_modules/selenium-cucumber-js/runtime/world.js:229:33
at ManagedPromise.invokeCallback_ (/var/lib/jenkins/workspace/unb-lib-tests/node_modules/selenium-webdriver/lib/promise.js:1341:14)
at TaskQueue.execute_ (/var/lib/jenkins/workspace/unb-lib-tests/node_modules/selenium-webdriver/lib/promise.js:2950:14)
at TaskQueue.executeNext_ (/var/lib/jenkins/workspace/unb-lib-tests/node_modules/selenium-webdriver/lib/promise.js:2933:27)
at asyncRun (/var/lib/jenkins/workspace/unb-lib-tests/node_modules/selenium-webdriver/lib/promise.js:2793:27)
at /var/lib/jenkins/workspace/unb-lib-tests/node_modules/selenium-webdriver/lib/promise.js:675:7
at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by Temi89** [comment]
@bricas I would have a look at it .

**Comment by john-doherty** [comment]
@bricas what version of node are you using?

**Comment by bricas** [comment]
I originally tested it against 7.x, now running 8.x (8.6, specifically) -- same error.

**Comment by john-doherty** [comment]
Have you tried removing an reinstalling node modules? `rm -rf node_modules && npm install`

**Comment by bricas** [comment]
it fails on a fresh install.

**Comment by john-doherty** [comment]
@Temi89 did you make any progress with this?

**Comment by john-doherty** [comment]
I've added some error checking around the eyes integration, can you try the latest version 1.5.2. If this fails, we need to back out the eyes integration work until @Temi89 has time to look at it

**Comment by bricas** [comment]
That seems to get rid of the eyes-related error i was seeing! Thanks.

**Comment by bricas** [comment]
👍

**Comment by Temi89** [comment]
@john-doherty  fixed the issue and checked in to my branch . Should have raised a pull request .
