### ISSUE TITLE
Reports are not being generated due an error

### ISSUE THREAD

**Issue by vhugogarcia** [john-doherty/selenium-cucumber-js#54]
Hello friends,

I'm experiencing an issue when the tests finished to run successfully or no. When it is trying to generate the HTML report, I get this message:

`/Users/demo/test/Projects/demo/demo.Automated.JS.Tests/node_modules/selenium-cucumber-js/node_modules/cucumber/lib/cucumber/runtime/event_broadcaster.js:30
            process.nextTick(function(){ throw error; }); // prevent swallow by unhandled rejection
                                         ^

TypeError: node_modules/selenium-cucumber-js/runtime/world.js:191 Cannot read property 'trim' of undefined
    at sanitize (/Users/demo/test/Projects/demo/demo.Automated.JS.Tests/node_modules/selenium-cucumber-js/node_modules/cucumber-html-reporter/lib/reporter.js:27:21)
    at generateReport (/Users/demo/test/Projects/demo/demo.Automated.JS.Tests/node_modules/selenium-cucumber-js/node_modules/cucumber-html-reporter/lib/reporter.js:52:24)
    at Object.generate (/Users/demo/test/Projects/demo/demo.Automated.JS.Tests/node_modules/selenium-cucumber-js/node_modules/cucumber-html-reporter/lib/reporter.js:419:9)
    at Object.generateReport [as generate] (/Users/demo/test/Projects/demo/demo.Automated.JS.Tests/node_modules/selenium-cucumber-js/node_modules/cucumber-html-reporter/index.js:30:21)
    at /Users/demo/test/Projects/demo/demo.Automated.JS.Tests/node_modules/selenium-cucumber-js/runtime/world.js:207:22
    at process._tickCallback (internal/process/next_tick.js:150:11)`

Do you know what library or setup is missing? 

Once again, I would like to say THANK YOU for this amazing library.

**Comment by pratyush23** [comment]
I am also facing the same issue. Were you able to fix this @vhugogarcia . Probably a compatibility issue with the cucumber version being used i.e. 1.3.3
