### ISSUE TITLE
page.mammothWorkwear undefined in buy-workwear-steps.js

### ISSUE THREAD

**Issue by rhowk** [john-doherty/selenium-cucumber-js#61]
https://github.com/john-doherty/selenium-cucumber-js/blob/7238c9bf966bab0ca0805445130c7754fb5e14aa/step-definitions/buy-workwear-steps.js#L6

gettting

`TypeError: Cannot read property 'url' of undefined
         at createWorld.<anonymous> (/Users/rhowk1271/Sites/time/_style/instyle/be-fe-instyle/features/step_definitions/buy-workwear-steps.js:6:53)
         at _combinedTickCallback (internal/process/next_tick.js:95:7)
         at process._tickCallback (internal/process/next_tick.js:161:9)
         at Function.Module.runMain (module.js:607:11)
         at startup (bootstrap_node.js:158:16)`
when I run the example using the directory structure cited at the end of the readme, and the command:
`node ./node_modules/selenium-cucumber-js/index.js -s ./features/step_definitions -p ./features/page_objects -o ./features/shared_objects -r ./features/reports
`
Thanks in advance for any help!

**Comment by rhowk** [comment]
renamed folder to _ instead of - and it works
