### ISSUE TITLE
Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:61285

### ISSUE THREAD

**Issue by badabam** [john-doherty/selenium-cucumber-js#8]
I install without errors and run a simple test, I get this error:

```shell
1) Scenario: Google search for nothing specific - features/google-search.feature:6
   Step: When I search Google for "nothing specific" - features/google-search.feature:7
   Step Definition: step-definitions/google-search-steps.js:3
   Message:
     Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:61285
         at ClientRequest.<anonymous> (/Users/me/some-project/node_modules/selenium-webdriver/http/index.js:238:15)
         at emitOne (events.js:96:13)
         at ClientRequest.emit (events.js:189:7)
         at Socket.socketErrorListener (_http_client.js:358:9)
         at emitOne (events.js:96:13)
         at Socket.emit (events.js:189:7)
         at emitErrorNT (net.js:1280:8)
         at _combinedTickCallback (internal/process/next_tick.js:74:11)
         at process._tickCallback (internal/process/next_tick.js:98:9)
     From: Task: WebDriver.createSession()
         at Function.createSession (/Users/me/some-project/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
         at Function.createSession (/Users/me/some-project/node_modules/selenium-webdriver/chrome.js:709:29)
         at createDriver (/Users/me/some-project/node_modules/selenium-webdriver/index.js:167:33)
         at Builder.build (/Users/me/some-project/node_modules/selenium-webdriver/index.js:639:16)
         at getDriverInstance (/Users/me/some-project/node_modules/selenium-cucumber-js/runtime/world.js:62:16)
         at /Users/me/some-project/node_modules/selenium-cucumber-js/runtime/world.js:149:29
```
I am on latest stable *macOS* and *Chrome 57* (also did not work with 56 though).

Any idea where to look at to fix this?

**Comment by john-doherty** [comment]
Hi @badabam, please can you install the latest version from NPM and try again?

**Comment by badabam** [comment]
Hi John, I'll do that tomorrow at work. Stay tuned!

**Comment by john-doherty** [comment]
Any luck @badabam?

**Comment by badabam** [comment]
Sorry, I cant' test this anymore. I got pulled from the project. 😞

**Comment by john-doherty** [comment]
No problem. I believe this issue is fixed so I will close this. Thanks

**Comment by dimonk87** [comment]
Hi @john-doherty! I have the same problem and don't know what I have to do! Bu the way, it worked yesterday, and I didn't make some new

**Comment by john-doherty** [comment]
Hi @dimonk87, what version of node are you using `node -v`?

I just tried a fresh install on node v9.1.0 and it worked fine.

**Comment by dimonk87** [comment]
Hello @john-doherty, I'm using v8.9.1

**Comment by john-doherty** [comment]
Thanks. That's very odd, I just tried a fresh install using 8.9.1 and it worked :-/

**Comment by john-doherty** [comment]
@dimonk87 I've updated the chromedriver version, please can you reinstall and try again?

**Comment by dimonk87** [comment]
@john-doherty, ok, I'll do it a little bit later

**Comment by dimonk87** [comment]
@john-doherty, Hello! It works! Thanks!

**Comment by john-doherty** [comment]
That's great news @dimonk87, thanks for your patience :)

**Comment by dimonk87** [comment]
@john-doherty, could I ask you for a favor? Can You recommend me some library for combine rest and ua? I try to use your framework with unirest, but it doesn't work for me

**Comment by john-doherty** [comment]
I tend to use [supertest](https://github.com/visionmedia/supertest). You should be able to get this working with this framework by writing the REST test within step definitions, just call the outer *done* when the test completes
